
package tmp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://tmp/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonWebService {


    /**
     * 
     * @return
     *     returns java.util.List<tmp.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://tmp/", className = "tmp.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://tmp/", className = "tmp.GetPersonsResponse")
    @Action(input = "http://tmp/PersonWebService/getPersonsRequest", output = "http://tmp/PersonWebService/getPersonsResponse")
    public List<Person> getPersons();

}
